In [28]:
import numpy as np
import pandas as pd 
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings("ignore")

In [29]:
sns.set_style("whitegrid")
plt.rcParams['figure.figsize']=(10,6)

In [30]:
df=pd.read_csv(r"C:\Users\DELL\Downloads\consumer_shopping_behavior_survey.csv")

In [31]:
df.shape

(500, 30)

In [32]:
df.head(5)

,Response_ID,Timestamp,Age,Gender,Occupation_Status,Country_Region,Monthly_Income_Range,Shop_Most_Where,Online_Shopping_Frequency,Preferred_Platform,...,Return_Frequency,Avg_Monthly_Spend_NonEssentials,Preferred_Payment_Method,Uses_BNPL_Installments,Online_Shopping_Satisfaction_Score,Trust_In_Online_Reviews_Score,Regret_After_Purchase_Frequency,Reason_Prefer_Online,Reason_Prefer_InStore,Best_Shopping_Mode
0,1,01/08/2026 12:30:25,20,Male,NaN,Philippines,"Under $1,000",Equal mix,Often,Physical stores,...,Never,Under $50,Digital wallet,"Yes, occasionally",6.0,7.0,2.0,More variety,No delivery wait,Online
1,2,21/06/2026 13:52:02,24,Male,Employed part-time,Brazil,"Under $1,000",In-store only,Often,Local e-commerce,...,Often,Under $50,Digital wallet,"No, never",5.0,8.0,3.0,NaN,Try product before buying,Offline
2,3,15/08/2026 04:24:18,22,Female,Student,India,"Under $1,000",Equal mix,Always,Local e-commerce,...,Sometimes,$150-300,Credit Card,"No, never",7.0,6.0,2.0,Better prices,Trust,Online
3,4,23/06/2026 21:24:21,20,Male,Student,NaN,"Under $1,000",In-store only,Occasionally,Brand websites,...,Never,Under $50,Debit Card,"No, never",8.0,7.0,3.0,Better prices,Try product before buying,Equal / both
4,5,20/08/2026 16:24:47,41,Male,Employed full-time,United States,"$1,000-3,000",Equal mix,Occasionally,NaN,...,Sometimes,$50-150,Debit Card,"No, never",6.0,8.0,2.0,Convenience,Trust,Equal / both

In [33]:
df.columns.to_list()

['Response_ID',
 'Timestamp',
 'Age',
 'Gender',
 'Occupation_Status',
 'Country_Region',
 'Monthly_Income_Range',
 'Shop_Most_Where',
 'Online_Shopping_Frequency',
 'Preferred_Platform',
 'Primary_Device',
 'Top_Spending_Category',
 'Review_Influence_Score',
 'Social_Ads_Influence_Score',
 'Price_Comparison_Frequency',
 'Discount_Importance_Score',
 'Follows_Brands_On_Social',
 'Likely_To_Buy_After_Ad_Score',
 'Makes_Shopping_List',
 'Impulse_Purchase_Frequency',
 'Return_Frequency',
 'Avg_Monthly_Spend_NonEssentials',
 'Preferred_Payment_Method',
 'Uses_BNPL_Installments',
 'Online_Shopping_Satisfaction_Score',
 'Trust_In_Online_Reviews_Score',
 'Regret_After_Purchase_Frequency',
 'Reason_Prefer_Online',
 'Reason_Prefer_InStore',
 'Best_Shopping_Mode']

In [34]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 30 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   Response_ID                         500 non-null    int64
 1   Timestamp                           500 non-null    str
 2   Age                                 478 non-null    str
 3   Gender                              484 non-null    str
 4   Occupation_Status                   479 non-null    str
 5   Country_Region                      480 non-null    str
 6   Monthly_Income_Range                479 non-null    str
 7   Shop_Most_Where                     484 non-null    str
 8   Online_Shopping_Frequency           481 non-null    str
 9   Preferred_Platform                  486 non-null    str
 10  Primary_Device                      492 non-null    str
 11  Top_Spending_Category               476 non-null    str
 12  Review_Influence_Score              485 non-null    float64
 13  Social_Ads_Influence_Score          479 non-null    float64
 14  Price_Comparison_Frequency          474 non-null    float64
 15  Discount_Importance_Score           477 non-null    float64
 16  Follows_Brands_On_Social            489 non-null    str
 17  Likely_To_Buy_After_Ad_Score        475 non-null    float64
 18  Makes_Shopping_List                 476 non-null    str
 19  Impulse_Purchase_Frequency          484 non-null    float64
 20  Return_Frequency                    483 non-null    str
 21  Avg_Monthly_Spend_NonEssentials     480 non-null    str
 22  Preferred_Payment_Method            485 non-null    str
 23  Uses_BNPL_Installments              488 non-null    str
 24  Online_Shopping_Satisfaction_Score  457 non-null    float64
 25  Trust_In_Online_Reviews_Score       450 non-null    float64
 26  Regret_After_Purchase_Frequency     448 non-null    float64
 27  Reason_Prefer_Online                446 non-null    str
 28  Reason_Prefer_InStore               455 non-null    str
 29  Best_Shopping_Mode                  449 non-null    str
dtypes: float64(9), int64(1), str(20)
memory usage: 211.0 KB

In [35]:
df.isnull().sum()

Response_ID                            0
Timestamp                              0
Age                                   22
Gender                                16
Occupation_Status                     21
Country_Region                        20
Monthly_Income_Range                  21
Shop_Most_Where                       16
Online_Shopping_Frequency             19
Preferred_Platform                    14
Primary_Device                         8
Top_Spending_Category                 24
Review_Influence_Score                15
Social_Ads_Influence_Score            21
Price_Comparison_Frequency            26
Discount_Importance_Score             23
Follows_Brands_On_Social              11
Likely_To_Buy_After_Ad_Score          25
Makes_Shopping_List                   24
Impulse_Purchase_Frequency            16
Return_Frequency                      17
Avg_Monthly_Spend_NonEssentials       20
Preferred_Payment_Method              15
Uses_BNPL_Installments                12
Online_Shopping_Satisfaction_Score    43
Trust_In_Online_Reviews_Score         50
Regret_After_Purchase_Frequency       52
Reason_Prefer_Online                  54
Reason_Prefer_InStore                 45
Best_Shopping_Mode                    51
dtype: int64

In [36]:
df.duplicated().sum()

np.int64(0)

In [37]:
df['Age']=pd.to_numeric(df['Age'],errors='coerce')
df['Timestamp']=pd.to_datetime(df['Timestamp'],format="%d/%m/%Y %H:%M:%S")

In [38]:
df[['Age','Timestamp']].dtypes

Age                 float64
Timestamp    datetime64[us]
dtype: object

In [39]:
df['Age'].describe()

count    470.000000
mean      25.019149
std        7.515276
min       16.000000
25%       20.000000
50%       22.000000
75%       30.000000
max       50.000000
Name: Age, dtype: float64

In [40]:
bins=[0,18,35,50,100]
labels=["Under 18","18-25","25-36","50+"]

df['Age_Group']=pd.cut(df['Age'],bins=bins,labels=labels)

In [41]:
df['Age_Group'].value_counts()

Age_Group
18-25       338
Under 18     78
25-36        54
50+           0
Name: count, dtype: int64

In [42]:
df.isnull().sum()

Response_ID                            0
Timestamp                              0
Age                                   30
Gender                                16
Occupation_Status                     21
Country_Region                        20
Monthly_Income_Range                  21
Shop_Most_Where                       16
Online_Shopping_Frequency             19
Preferred_Platform                    14
Primary_Device                         8
Top_Spending_Category                 24
Review_Influence_Score                15
Social_Ads_Influence_Score            21
Price_Comparison_Frequency            26
Discount_Importance_Score             23
Follows_Brands_On_Social              11
Likely_To_Buy_After_Ad_Score          25
Makes_Shopping_List                   24
Impulse_Purchase_Frequency            16
Return_Frequency                      17
Avg_Monthly_Spend_NonEssentials       20
Preferred_Payment_Method              15
Uses_BNPL_Installments                12
Online_Shopping_Satisfaction_Score    43
Trust_In_Online_Reviews_Score         50
Regret_After_Purchase_Frequency       52
Reason_Prefer_Online                  54
Reason_Prefer_InStore                 45
Best_Shopping_Mode                    51
Age_Group                             30
dtype: int64

In [45]:
cols_to_fill=['Gender','Occupation_Status','Country_Region','Shop_Most_Where','Preferred_Platform','Preferred_Payment_Method']

In [47]:
df.columns

Index(['Response_ID', 'Timestamp', 'Age', 'Gender', 'Occupation_Status',
       'Country_Region', 'Monthly_Income_Range', 'Shop_Most_Where',
       'Online_Shopping_Frequency', 'Preferred_Platform', 'Primary_Device',
       'Top_Spending_Category', 'Review_Influence_Score',
       'Social_Ads_Influence_Score', 'Price_Comparison_Frequency',
       'Discount_Importance_Score', 'Follows_Brands_On_Social',
       'Likely_To_Buy_After_Ad_Score', 'Makes_Shopping_List',
       'Impulse_Purchase_Frequency', 'Return_Frequency',
       'Avg_Monthly_Spend_NonEssentials', 'Preferred_Payment_Method',
       'Uses_BNPL_Installments', 'Online_Shopping_Satisfaction_Score',
       'Trust_In_Online_Reviews_Score', 'Regret_After_Purchase_Frequency',
       'Reason_Prefer_Online', 'Reason_Prefer_InStore', 'Best_Shopping_Mode',
       'Age_Group'],
      dtype='str')

In [46]:
for col in cols_to_fill:
    df[col]=df[col].fillna('Unknown')

In [48]:
last6=['Online_Shopping_Satisfaction_Score',
       'Trust_In_Online_Reviews_Score', 'Regret_After_Purchase_Frequency',
       'Reason_Prefer_Online', 'Reason_Prefer_InStore', 'Best_Shopping_Mode']

In [50]:
dropoff=df[last6].isna().all(axis=1)

In [51]:
dropoff.sum()

np.int64(30)

In [54]:
df.loc[dropoff,'Timestamp'].dt.date.value_counts().sort_index()

Timestamp
2026-06-20    1
2026-06-22    1
2026-06-24    1
2026-06-29    1
2026-06-30    1
2026-07-02    1
2026-07-03    1
2026-07-05    1
2026-07-06    1
2026-07-07    2
2026-07-09    1
2026-07-10    1
2026-07-16    1
2026-07-24    2
2026-07-27    2
2026-07-28    1
2026-07-30    1
2026-08-02    1
2026-08-03    1
2026-08-15    2
2026-08-16    1
2026-08-17    1
2026-08-18    1
2026-08-19    1
2026-08-21    1
2026-08-24    1
Name: count, dtype: int64

In [55]:
pd.crosstab(df['Shop_Most_Where'],df['Reason_Prefer_InStore'],dropna=False)

Reason_Prefer_InStore,No delivery wait,Not applicable,Trust,Try product before buying,NaN
Shop_Most_Where,,,,,
Equal mix,54,42,49,74,29
In-store only,15,10,16,21,9
Online only,43,20,51,46,5
Unknown,7,0,3,4,2